apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          env:
            - name: SLACK_CHANNEL
              value: general
            - name: SLACK_URL
              value: https://hooks.slack.com/services/TOKEN
            - name: SLACK_USER
              value: alertmanager
          image: stefanprodan/swarmprom-alertmanager:v0.14.0
          name: alertmanager
          resources:
            limits:
              memory: "134217728"
            requests:
              memory: "67108864"
          volumeMounts:
            - mountPath: /alertmanager
              name: alertmanager
      restartPolicy: Always
      volumes:
        - name: alertmanager
          persistentVolumeClaim:
            claimName: alertmanager
status: {}
