apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9093"
      port: 9093
      targetPort: 9093
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: caddy
status:
  loadBalancer: {}
