apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: caddy
    spec:
      containers:
        - env:
            - name: ADMIN_PASSWORD
              value: admin
            - name: ADMIN_USER
              value: admin
          image: stefanprodan/caddy
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3000
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 1
          name: caddy
          ports:
            - containerPort: 3000
            - containerPort: 9090
            - containerPort: 9093
            - containerPort: 9094
          resources:
            limits:
              memory: "134217728"
            requests:
              memory: "67108864"
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-config
              subPath: Caddyfile
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: Caddyfile
                path: Caddyfile
            name: caddy-config
          name: caddy-config
status: {}
