apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-site2
spec:
  # The storageClassName should be set to null, 
  #   because this PV is not created using dynamic provisioning.
  storageClassName: ""

  capacity:
    storage: 20Mi

  accessModes:
    - ReadWriteMany

  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
