apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-site2
spec:
  accessModes:
    - ReadWriteMany

  # The storageClassName should be set to null, 
  #   because this PVC is not created using dynamic provisioning.
  storageClassName: ""

  resources:
    requests:
      storage: 10Mi

  volumeName: "pv-nfs-site2"

